var HK_BANK_DATABASE = [
    { code: '004', nameZh: '香港上海滙豐銀行有限公司', nameEn: 'The Hongkong and Shanghai Banking Corporation Limited' },
    { code: '012', nameZh: '中國銀行(香港)有限公司', nameEn: 'Bank of China (Hong Kong) Limited' },
    { code: '003', nameZh: '渣打銀行(香港)有限公司', nameEn: 'Standard Chartered Bank (Hong Kong) Limited' },
    { code: '024', nameZh: '恒生銀行有限公司', nameEn: 'Hang Seng Bank Limited' },
    { code: '015', nameZh: '東亞銀行有限公司', nameEn: 'The Bank of East Asia, Limited' },
    { code: '035', nameZh: '華僑銀行(香港)有限公司', nameEn: 'OCBC Bank (Hong Kong) Limited' },
    { code: '020', nameZh: '招商永隆銀行有限公司', nameEn: 'CMB Wing Lung Bank Limited' },
    { code: '039', nameZh: '集友銀行有限公司', nameEn: 'Chiyu Banking Corporation Limited' },
    { code: '028', nameZh: '大眾銀行(香港)有限公司', nameEn: 'Public Bank (Hong Kong) Limited' },
    { code: '072', nameZh: '中國工商銀行(亞洲)有限公司', nameEn: 'Industrial and Commercial Bank of China (Asia) Limited' },
    { code: '006', nameZh: '花旗銀行(香港)有限公司', nameEn: 'Citibank (Hong Kong) Limited' },
    { code: '016', nameZh: '星展銀行(香港)有限公司', nameEn: 'DBS Bank (Hong Kong) Limited' },
    { code: '043', nameZh: '南洋商業銀行有限公司', nameEn: 'Nanyang Commercial Bank, Limited' },
    { code: '025', nameZh: '上海商業銀行有限公司', nameEn: 'Shanghai Commercial Bank Limited' },
    { code: '041', nameZh: '創興銀行有限公司', nameEn: 'Chong Hing Bank Limited' },
    { code: '040', nameZh: '大新銀行有限公司', nameEn: 'Dah Sing Bank, Limited' },
    { code: '250', nameZh: '交通銀行(香港)有限公司', nameEn: 'Bank of Communications (Hong Kong) Limited' },
    { code: '387', nameZh: '眾安銀行有限公司 (ZA Bank)', nameEn: 'ZA Bank Limited' },
    { code: '388', nameZh: '滙立銀行有限公司 (Airstar Bank)', nameEn: 'Airstar Bank Limited' },
    { code: '389', nameZh: 'Mox Bank Limited', nameEn: 'Mox Bank Limited' },
    { code: '390', nameZh: 'Livi Bank Limited', nameEn: 'Livi Bank Limited' }
];
